<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Invalid Username being used during the Negative Login Test Case</description>
   <name>Invalid Username Input</name>
   <tag></tag>
   <elementGuidId>f854a16b-ab26-4c00-a354-b1fadba057f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginusername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginusername</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62c90225-9e56-4756-81d0-aef3a6107bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>501a902b-b62e-470e-8223-da65f194e5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>371eded3-3cef-4ab3-b119-042f6ecb0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginusername</value>
      <webElementGuid>39770489-e4d5-46f9-94e5-b7973d998c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginusername&quot;)</value>
      <webElementGuid>0e5a3876-ef09-4d37-ade7-cb7731e00168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginusername']</value>
      <webElementGuid>3abb073d-b6a3-4095-b5e7-5c2a92c72077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logInModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>853f2816-37da-4194-83e7-0a86d0ce3af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div/input</value>
      <webElementGuid>61bae6f8-4a70-4c0a-9ca5-a567c764ceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginusername']</value>
      <webElementGuid>9c058be8-3d8a-4a2b-b5e6-4a60cbd65288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
